config/routes.rb
Rails.application.routes.draw do
  get 'homes/about' => 'homes#about', as:"about"
  devise_for :users
  root to: "homes#top"
  resources :books, only: [:new, :edit, :index, :show, :create, :destroy]
  resources :users, only: [:show, :edit, :index, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
    def get_profile_image(width,height)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
    profile_image.variant(resize_to_limit: [width, height]).processed
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user! ,except:[:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
        user_path(current_user)
    end
    
    def after_sign_out_path_for(resource)
        root_path
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def top
    end
    
    def new
        @book = Book.new
    end
    
    def index
        @user = current_user
        @books = Book.all
    end
    
    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            flash[:notice] = 'You have created book successfully.'
            redirect_to book_path(@book.id)
        else
            @books = Book.all
            render :index
        end
    end
    
    def show
        @book = Book.find(params[:id])
        @user = @book.user
        @books = @user.books
    end
    
    def edit
    end
    
    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to '/books'
    end
    
    private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id])
        @books = @user.books 
        @book = Book.new
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
    def index
        @book = Book.new
        @user = current_user
        @users = User.all
    end
    
    
    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to current_user
    end


    private

    def user_params
        params.require(:user).permit(:name, :profile_image, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h2>Book edit</h2>

app/views/books/index.html.erb
<h2>index</h2>

<div class="hidari">
    <div>
        <%= image_tag @user.get_profile_image(100,100) %>
        <h3>name</h3>
        <%= @user.name %>
        <h3>introduction</h3>
        <%= @user.introduction %>
    </div>
    
        <p>
            <% if @user == current_user %>
                <%= link_to edit_user_path(current_user.id) do %>
                    <i class="fas fa-user-cog"></i>
                <%end%>
            <% else %>
                <%= link_to user_path(current_user.id) do %>
                    <i class="fas fa-user-cog"></i>
                <%end%>
            <%end%>
        </p>
</div>
<div class="migi">
    <% @books.each do |book| %>
        <span><%= image_tag book.user.get_profile_image(100,100) %></span>
        <%= link_to book_path(book.id) do %>
            <span><%= book.title %></span>
        <%end%>
        <span><%= book.body %></span>
    <%end%>
</div>

app/views/books/show.html.erb
<h2>book show</h2>
<div>
    <div class="hidari">
        <div>
            <%= image_tag @user.get_profile_image(100,100) %>
            <h3>name</h3>
            <%= @user.name %>
            <h3>introduction</h3>
            <%= @user.introduction %>
        </div>
        <p>
            <% if @user == current_user %>
                <%= link_to edit_user_path(current_user.id) do %>
                    <i class="fas fa-user-cog"></i>
                <%end%>
            <% else %>
                <%= link_to user_path(current_user.id) do %>
                    <i class="fas fa-user-cog"></i>
                <%end%>
            <%end%>
        </p>
  
        <h2>New Book</h2>

        <%= form_with model: @book do |f| %>
            <div class="sounyu">
            <h4 class="create">Title</h4>
            <%= f.text_field :title %>
            </div>
            <div class="sounyu">
            <h4 class="create">Opinion</h4>
            <%= f.text_area :body %>
            </div>
            <p class="create create2"><%= f.submit 'Create Book' %></p>
        <% end %>
    </div>
    <div class="migi">
        <span><%= image_tag @book.user.get_profile_image(100,100) %></span>
        <span>
            <%= link_to user_path(@book.user.id) do %>
                <span><%= @book.user.name %></span>
            <%end%>
        </span>
        <span>
            <%= link_to book_path(@book.id) do %>
                <span><%= @book.title %></span>
            <%end%>
        </span>
        <span><%= @book.body %></span>
        <% if @book.user == current_user %>
            <span><%= link_to "Edit", edit_book_path(@book.id) %></span>
            <span><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %></span>
        <%end%>
</div>

app/views/homes/about.html.erb
<main>
    <h1>welcome to <i class="fa-solid fa-book"></i><strong> Bookers</strong> !!</h1>
</main>
<footer>
    <div>CopyRight Infratop.inc</div>
</footer>

app/views/homes/top.html.erb
<main>
    <h1>welcome to <i class="fa-solid fa-book"></i><strong> Bookers</strong> !!</h1>
    <p>In <i class="fa-solid fa-book"></i><strong> Bookers</strong>,</p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>
    <div><a href="/users/sign_in">Log in</a></div>
    <div><a href="/users/sign_up">Sign up</a></div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/11e3061d58.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <div class="headerwaku">
        <div class="ookisasitei"></div>
        <p class="books_home">
          <a href="/"><p>Bookers</p></a>
        </p>
        <div class="headermigi">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id) do %>
              <i class="fas fa-home"></i>
              Home
            <%end%>
          </li>
          <li>
            <%= link_to users_path do %>
              <i class="fas fa-users"></i>
              Users
            <%end%>
          </li>
          <li>
            <%= link_to books_path do %>
              <i class="fas fa-user-plus"></i>
              Books
            <%end%>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>
              Log out
            <%end%>
          </li>
        <% else %>
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
              Home
            <%end%>
          </li>
          <li>
            <%= link_to about_path do %>
              <i class="fas fa-link"></i>
              About
            <%end%>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
              <i class="fas fa-user-plus"></i>
              Sign up
            <%end%>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt"></i>
              Log in
            <%end%>
          </li>
        <% end %>
        </div>
        </div>
        </div>
      </header>
      
    <%= yield %>
      <footer>
        <p>CopyRight Infratop.inc</p>
      </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_with model: @user do |f| %>
    <label for="inputName">Name</label>
    <%= f.text_field :name, autofocus: true, id:"inputName"%>
    <label for="inputImage">Image</label>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
    <label for="inputIntroduction">Introduction</label>
    <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction"%>
    <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div>
    <div class="hidari">
        <div>
            <%= image_tag @user.get_profile_image(100,100) %>
            <h3>name</h3>
            <%= @user.name %>
            <h3>introduction</h3>
            <%= @user.introduction %>
        </div>
        <p>
            <% if @user == current_user %>
                <%= link_to edit_user_path(current_user.id) do %>
                    <i class="fas fa-user-cog"></i>
                <%end%>
            <% else %>
                <%= link_to user_path(current_user.id) do %>
                    <i class="fas fa-user-cog"></i>
                <%end%>
            <%end%>
        </p>
  
        <h2>New Book</h2>

        <%= form_with model: @book do |f| %>
            <div class="sounyu">
            <h4 class="create">Title</h4>
            <%= f.text_field :title %>
            </div>
            <div class="sounyu">
            <h4 class="create">Opinion</h4>
            <%= f.text_area :body %>
            </div>
            <p class="create create2"><%= f.submit 'Create Book' %></p>
        <% end %>
    </div>
    <div class="migi">
        <% @users.each do |user| %>
        <span><%= image_tag user.get_profile_image(100,100) %></span>
        <span><%= user.name %></span>
        <%= link_to "Show", user_path(user.id) %>
        <%end%>
    </div>
</div>

app/views/users/show.html.erb
<div>
  <div class="hidari">
    <div>
      <%= image_tag @user.get_profile_image(100,100) %>
      <h3>name</h3>
      <%= @user.name %>
      <h3>introduction</h3>
      <%= @user.introduction %>
    </div>
  
    <p>
      <% if @user == current_user %>
        <%= link_to edit_user_path(current_user.id) do %>
          <i class="fas fa-user-cog"></i>
        <%end%>
      <% else %>
        <%= link_to user_path(current_user.id) do %>
          <i class="fas fa-user-cog"></i>
        <%end%>
      <%end%>
    </p>  
  
    <h2>New Book</h2>
    <div id="error">
    <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this book from being saved:>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    </div>

    <%= form_with model: @book do |f| %>
      <div class="sounyu">
      <h4 class="create">Title</h4>
      <%= f.text_field :title %>
      </div>
      <div class="sounyu">
      <h4 class="create">Opinion</h4>
      <%= f.text_area :body %>
      </div>
      <p class="create create2"><%= f.submit 'Create Book' %></p>
    <% end %>
  </div>
  <div class="migi">
    <% @books.each do |book| %>
      <span><%= image_tag book.user.get_profile_image(100,100) %></span>
      <span>
        <%= link_to book_path(book.id) do %>
        <span><%= book.title %></span>
        <%end%>
      </span>
      <span><%= book.body %></span>
    <%end%>
  </div>
</div>